using System.Collections.Generic;
using UnityEngine;

public class PayoutCalculation : MonoBehaviour
{
    [SerializeField] private List<GameObject> LineObjects;
    internal List<int> DontDestroyLines = new List<int>();


    //generate lines at runtime accordingly
    internal void GeneratePayoutLinesBackend(int index = -1, bool DestroyFirst = true)
    {
        if (DestroyFirst)
            ResetStaticLine();

        if (index >= 0)
        {
            LineObjects[index].SetActive(true);
            return;
        }
        DontDestroyLines.Clear();
        for (int i = 0; i < LineObjects.Count; i++)
        {
            LineObjects[i].SetActive(true);
        }
    }

    //delete the line generated by button hover
    internal void ResetStaticLine()
    {
        for (int i = 0; i < LineObjects.Count; i++)
        {
            if (DontDestroyLines.Contains(i))
                continue;
            else
                LineObjects[i].SetActive(false);
        }
    }
}
